version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd design-system && npm install
            - run: cd design-system && npm test
            - run: cd design-system && npx chromatic --project-token=wx8a9anyfh --exit-zero-on-changes
            - run: |
                if [ $CIRCLE_BRANCH = "master" ]
                then
                  cd design-system && yarn release
                fi
workflows:
  build-and-test:
    jobs:
      - build-and-test
